# Copyright (C) 2021 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/lt02wifi/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/lt02wifi/proprietary/etc/firmware/mrvl/WlanCalData_ext.conf:system/etc/firmware/mrvl/WlanCalData_ext.conf \
    vendor/samsung/lt02wifi/proprietary/etc/firmware/mrvl/WlanCalData_ext.conf_0:system/etc/firmware/mrvl/WlanCalData_ext.conf_0 \
    vendor/samsung/lt02wifi/proprietary/etc/firmware/mrvl/WlanCalData_ext.conf_ve:system/etc/firmware/mrvl/WlanCalData_ext.conf_ve \
    vendor/samsung/lt02wifi/proprietary/etc/firmware/mrvl/bt_cal_data.conf:system/etc/firmware/mrvl/bt_cal_data.conf \
    vendor/samsung/lt02wifi/proprietary/etc/firmware/mrvl/bt_init_cfg.conf:system/etc/firmware/mrvl/bt_init_cfg.conf \
    vendor/samsung/lt02wifi/proprietary/etc/firmware/mrvl/cal_data.conf:system/etc/firmware/mrvl/cal_data.conf \
    vendor/samsung/lt02wifi/proprietary/etc/firmware/mrvl/reg_alpha2:system/etc/firmware/mrvl/reg_alpha2 \
    vendor/samsung/lt02wifi/proprietary/etc/firmware/mrvl/revision_ve:system/etc/firmware/mrvl/revision_ve \
    vendor/samsung/lt02wifi/proprietary/etc/firmware/mrvl/sd8787_uapsta.bin:system/etc/firmware/mrvl/sd8787_uapsta.bin \
    vendor/samsung/lt02wifi/proprietary/etc/firmware/mrvl/txpwrlimit_cfg.conf:system/etc/firmware/mrvl/txpwrlimit_cfg.conf \
    vendor/samsung/lt02wifi/proprietary/etc/firmware/mrvl/txpwrlimit_cfg.conf_ve:system/etc/firmware/mrvl/txpwrlimit_cfg.conf_ve \
    vendor/samsung/lt02wifi/proprietary/etc/firmware/mrvl/w8787_wlan_SDIO_bt_SDIO.bin:system/etc/firmware/mrvl/w8787_wlan_SDIO_bt_SDIO.bin \
    vendor/samsung/lt02wifi/proprietary/lib/egl/libEGL_MRVL.so:system/lib/egl/libEGL_MRVL.so \
    vendor/samsung/lt02wifi/proprietary/lib/egl/libGLESv1_CM_MRVL.so:system/lib/egl/libGLESv1_CM_MRVL.so \
    vendor/samsung/lt02wifi/proprietary/lib/egl/libGLESv2_MRVL.so:system/lib/egl/libGLESv2_MRVL.so \
    vendor/samsung/lt02wifi/proprietary/lib/hw/gralloc.mrvl.so:system/lib/hw/gralloc.mrvl.so \
    vendor/samsung/lt02wifi/proprietary/lib/libGAL.so:system/lib/libGAL.so \
    vendor/samsung/lt02wifi/proprietary/lib/libgcu.so:system/lib/libgcu.so \
    vendor/samsung/lt02wifi/proprietary/lib/libgputex.so:system/lib/libgputex.so \
    vendor/samsung/lt02wifi/proprietary/lib/libmvmem.so:system/lib/libmvmem.so
